### ISSUE TITLE
[Bug]: after accepting healing transaction, nothing happens

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. starting healing transaction
2. accepted transcation 
3. conformation recieved from meta mask of transaction
4. no respones from game
5. try and heal again and error direct heal is no allowqed
6.after leaving and returning to hut "calculating price appears, with same error if i push button
7.hard refresh and then heath appears

![image](https://user-images.githubusercontent.com/120995580/208740888-e5dd322c-5903-4749-aec9-2132982488a8.png)

![image](https://user-images.githubusercontent.com/120995580/208740815-6cefad9e-d570-4846-8599-75e963b72353.png)

### What browsers are you seeing the problem on?

Brave

### Relevant log output / error message

```shell
DevTools failed to load source map: Could not load content for chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/web_interfaceBundle.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/keychainifyBundle.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
.png:1          GET https://cdn.dragoncrypto.io/encounters/.png 404
Image (async)
Fr @ runtime-dom.esm-bundler.js:277
ti @ runtime-dom.esm-bundler.js:409
S @ runtime-core.esm-bundler.js:4632
A @ runtime-core.esm-bundler.js:4595
m @ runtime-core.esm-bundler.js:4515
O @ runtime-core.esm-bundler.js:4714
S @ runtime-core.esm-bundler.js:4623
A @ runtime-core.esm-bundler.js:4595
m @ runtime-core.esm-bundler.js:4515
O @ runtime-core.esm-bundler.js:4714
S @ runtime-core.esm-bundler.js:4623
A @ runtime-core.esm-bundler.js:4595
m @ runtime-core.esm-bundler.js:4515
O @ runtime-core.esm-bundler.js:4714
j @ runtime-core.esm-bundler.js:4885
m @ runtime-core.esm-bundler.js:4511
O @ runtime-core.esm-bundler.js:4714
S @ runtime-core.esm-bundler.js:4623
A @ runtime-core.esm-bundler.js:4595
m @ runtime-core.esm-bundler.js:4515
s @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
L @ runtime-core.esm-bundler.js:5185
N @ runtime-core.esm-bundler.js:4968
P @ runtime-core.esm-bundler.js:4926
m @ runtime-core.esm-bundler.js:4518
s @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
L @ runtime-core.esm-bundler.js:5185
N @ runtime-core.esm-bundler.js:4968
P @ runtime-core.esm-bundler.js:4926
m @ runtime-core.esm-bundler.js:4518
O @ runtime-core.esm-bundler.js:4714
S @ runtime-core.esm-bundler.js:4623
A @ runtime-core.esm-bundler.js:4595
m @ runtime-core.esm-bundler.js:4515
s @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
L @ runtime-core.esm-bundler.js:5185
N @ runtime-core.esm-bundler.js:4968
P @ runtime-core.esm-bundler.js:4926
m @ runtime-core.esm-bundler.js:4518
s @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
ze @ runtime-core.esm-bundler.js:155
mt @ runtime-core.esm-bundler.js:394
Promise.then (async)
dt @ runtime-core.esm-bundler.js:285
st @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
T @ reactivity.esm-bundler.js:382
Ce @ reactivity.esm-bundler.js:990
(anonymous) @ reactivity.esm-bundler.js:1113
T @ reactivity.esm-bundler.js:382
Ce @ reactivity.esm-bundler.js:990
set value @ reactivity.esm-bundler.js:1026
V @ vue-router.esm-bundler.js:3194
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
F @ vue-router.esm-bundler.js:3038
C @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:3834
56d7 @ main.js:13
o @ bootstrap:89
0 @ app.00501ae0.js:1
o @ bootstrap:89
n @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.00501ae0.js:1
mixpanel.cjs.js:4521          POST https://api-js.mixpanel.com/engage/?verbose=1&ip=1&_=1671560975977 net::ERR_BLOCKED_BY_CLIENT
$e._send_request @ mixpanel.cjs.js:4521
(anonymous) @ mixpanel.cjs.js:4604
J.flush @ mixpanel.cjs.js:2490
play-beta:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
CombatButtons.vue:204 1
CombatButtons.vue:204 1
index.esm2017.js:71          POST https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Faurum-dfe01%2Fdatabases%2F(default)&VER=8&gsessionid=6kiUuARqbI53MHb3XM-cQ-qVFOY7MBjg9QUuYo1m-zY&SID=UufTkXBlAMofPU79EQIh9w&RID=13954&TYPE=terminate&zx=2dzgwr51hekx net::ERR_BLOCKED_BY_CLIENT
ea @ index.esm2017.js:71
_a.close @ index.esm2017.js:84
zr @ index.esm2017.js:12108
close @ index.esm2017.js:11927
close @ index.esm2017.js:12489
Oo @ index.esm2017.js:12450
(anonymous) @ index.esm2017.js:12441
(anonymous) @ index.esm2017.js:13341
(anonymous) @ index.esm2017.js:16365
(anonymous) @ index.esm2017.js:16398
Promise.then (async)
Ga @ index.esm2017.js:16398
enqueue @ index.esm2017.js:16365
enqueueAndForget @ index.esm2017.js:16343
handleDelayElapsed @ index.esm2017.js:13340
(anonymous) @ index.esm2017.js:13322
setTimeout (async)
start @ index.esm2017.js:13322
createAndSchedule @ index.esm2017.js:13316
enqueueAfterDelay @ index.esm2017.js:16438
Mo @ index.esm2017.js:12441
dr @ index.esm2017.js:12928
(anonymous) @ index.esm2017.js:14273
Promise.then (async)
ti @ index.esm2017.js:14272
Hr @ index.esm2017.js:13595
(anonymous) @ index.esm2017.js:15688
(anonymous) @ index.esm2017.js:16365
(anonymous) @ index.esm2017.js:16398
Promise.then (async)
Ga @ index.esm2017.js:16398
enqueue @ index.esm2017.js:16365
enqueueAndForget @ index.esm2017.js:16343
next @ index.esm2017.js:15688
(anonymous) @ index.esm2017.js:15166
setTimeout (async)
pa @ index.esm2017.js:15165
next @ index.esm2017.js:15156
Du @ index.esm2017.js:13691
Ru @ index.esm2017.js:13654
zr @ index.esm2017.js:13604
pi @ index.esm2017.js:14571
await in pi (async)
ai @ index.esm2017.js:14351
await in ai (async)
(anonymous) @ index.esm2017.js:13056
yr @ index.esm2017.js:13026
await in yr (async)
onMessage @ index.esm2017.js:12583
(anonymous) @ index.esm2017.js:12529
(anonymous) @ index.esm2017.js:12552
(anonymous) @ index.esm2017.js:16365
(anonymous) @ index.esm2017.js:16398
Promise.then (async)
Ga @ index.esm2017.js:16398
enqueue @ index.esm2017.js:16365
enqueueAndForget @ index.esm2017.js:16343
(anonymous) @ index.esm2017.js:12552
(anonymous) @ index.esm2017.js:12529
so @ index.esm2017.js:11939
(anonymous) @ index.esm2017.js:12163
(anonymous) @ index.esm2017.js:12114
Te @ index.esm2017.js:27
Se @ index.esm2017.js:25
Ma.wa @ index.esm2017.js:86
Bt @ index.esm2017.js:43
Ot @ index.esm2017.js:38
a.Ia @ index.esm2017.js:36
a.gb @ index.esm2017.js:34
Te @ index.esm2017.js:27
Se @ index.esm2017.js:25
Gn @ index.esm2017.js:65
a.cb @ index.esm2017.js:64
a.Fa @ index.esm2017.js:64
Nn @ index.esm2017.js:60
a.Sa @ index.esm2017.js:58
Promise.then (async)
jn @ index.esm2017.js:58
a.Va @ index.esm2017.js:58
Promise.then (async)
a.send @ index.esm2017.js:55
a.ea @ index.esm2017.js:62
St @ index.esm2017.js:33
ba @ index.esm2017.js:78
a.Ga @ index.esm2017.js:77
Fe @ index.esm2017.js:28
Promise.then (async)
Ce @ index.esm2017.js:28
Be @ index.esm2017.js:28
da @ index.esm2017.js:76
Bt @ index.esm2017.js:43
Ot @ index.esm2017.js:38
a.Ia @ index.esm2017.js:36
a.gb @ index.esm2017.js:34
Te @ index.esm2017.js:27
Se @ index.esm2017.js:25
Gn @ index.esm2017.js:65
a.cb @ index.esm2017.js:64
a.Fa @ index.esm2017.js:64
Nn @ index.esm2017.js:60
a.Sa @ index.esm2017.js:58
Promise.then (async)
jn @ index.esm2017.js:58
a.Va @ index.esm2017.js:58
Promise.then (async)
a.send @ index.esm2017.js:55
a.ea @ index.esm2017.js:62
St @ index.esm2017.js:33
At @ index.esm2017.js:33
a.Ha @ index.esm2017.js:74
Fe @ index.esm2017.js:28
CombatButtons.vue:204 1
CombatButtons.vue:204 1
index.js:671 {success: true, consumeResult: {…}, enemyHit: {…}, heroStats: {…}}
index.js:673 heal success 150
index.js:681 healitem Proxy {id: 4, staticId: 10002, name: 'Healing Potion', type: 'consumable', imageName: 'Res_40.png', …}
Combat.vue:446 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scroll')
    at j (Combat.vue:446:18)
    at Combat.vue:353:9
    at f (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at a (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:25:9)
j @ Combat.vue:446
(anonymous) @ Combat.vue:353
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
a @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Combat.vue:192
a.emit @ index.mjs:136
emitEvent @ socket.js:278
onevent @ socket.js:265
onpacket @ socket.js:235
a.emit @ index.mjs:136
ondecoded @ manager.js:200
a.emit @ index.mjs:136
add @ index.js:124
ondata @ manager.js:192
a.emit @ index.mjs:136
onPacket @ socket.js:323
a.emit @ index.mjs:136
onPacket @ transport.js:105
onData @ transport.js:97
ws.onmessage @ websocket.js:79
HealersHut.vue:228 Heal Price: 2.7695226
mixpanel.cjs.js:4521          POST https://api-js.mixpanel.com/track/?verbose=1&ip=1&_=1671561100426 net::ERR_BLOCKED_BY_CLIENT
$e._send_request @ mixpanel.cjs.js:4521
(anonymous) @ mixpanel.cjs.js:4604
J.flush @ mixpanel.cjs.js:2490
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
setTimeout (async)
J.scheduleFlush @ mixpanel.cjs.js:2355
J.resetFlush @ mixpanel.cjs.js:2346
J.flush @ mixpanel.cjs.js:2395
(anonymous) @ mixpanel.cjs.js:4268
(anonymous) @ mixpanel.cjs.js:4278
inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
await in _processRequest (async)
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
(anonymous) @ inpage.js:1
request @ inpage.js:1
(anonymous) @ web3-provider.js:65
send @ web3-provider.js:129
(anonymous) @ json-rpc-provider.js:515
(anonymous) @ json-rpc-provider.js:8
h @ json-rpc-provider.js:4
perform @ json-rpc-provider.js:492
(anonymous) @ base-provider.js:1531
c @ base-provider.js:5
Promise.then (async)
s @ base-provider.js:7
c @ base-provider.js:5
Promise.then (async)
s @ base-provider.js:7
(anonymous) @ base-provider.js:8
g @ base-provider.js:4
estimateGas @ base-provider.js:1526
sendUncheckedTransaction @ json-rpc-provider.js:187
(anonymous) @ json-rpc-provider.js:231
c @ json-rpc-provider.js:5
Promise.then (async)
s @ json-rpc-provider.js:7
(anonymous) @ json-rpc-provider.js:8
h @ json-rpc-provider.js:4
sendTransaction @ json-rpc-provider.js:227
(anonymous) @ index.js:323
c @ index.js:5
Promise.then (async)
s @ index.js:7
(anonymous) @ index.js:8
h @ index.js:4
(anonymous) @ index.js:312
(anonymous) @ HealersHut.vue:326
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
a @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ HealersHut.vue:320
a.isDead.a.needsHeal.a.isDCAUApproved.a.hasDCAU.a.isHealing.a.isFetchingHealPrice.Object.onClick.t.<computed>.t.<computed> @ HealersHut.vue:79
(anonymous) @ runtime-dom.esm-bundler.js:383
ze @ runtime-core.esm-bundler.js:155
Ve @ runtime-core.esm-bundler.js:164
Ve @ runtime-core.esm-bundler.js:174
n @ runtime-dom.esm-bundler.js:369
HealersHut.vue:347 {code: -32603, message: 'Internal JSON-RPC error.', data: {…}, stack: '{\n  "code": -32603,\n  "message": "Internal JSON-RP…hfbeogaeaoehlefnkodbefgpgknn/common-6.js:19:37692'}
helpers.js:13 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000164449524543545f4845414c5f444953414c4c4f57454400000000000000000000
index.esm2017.js:71          POST https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel?database=projects%2Faurum-dfe01%2Fdatabases%2F(default)&VER=8&gsessionid=ZAvh72mJ_mRaMWoPU311ISa33Vo1Ne2IGCwQuUewkok&SID=qjJ5ifganeUYfr4VHY4epA&RID=84762&TYPE=terminate&zx=ru4aznldmk82 net::ERR_BLOCKED_BY_CLIENT
ea @ index.esm2017.js:71
_a.close @ index.esm2017.js:84
zr @ index.esm2017.js:12108
close @ index.esm2017.js:11927
close @ index.esm2017.js:12489
Oo @ index.esm2017.js:12450
(anonymous) @ index.esm2017.js:12441
(anonymous) @ index.esm2017.js:13341
(anonymous) @ index.esm2017.js:16365
(anonymous) @ index.esm2017.js:16398
Promise.then (async)
Ga @ index.esm2017.js:16398
enqueue @ index.esm2017.js:16365
enqueueAndForget @ index.esm2017.js:16343
handleDelayElapsed @ index.esm2017.js:13340
(anonymous) @ index.esm2017.js:13322
setTimeout (async)
start @ index.esm2017.js:13322
createAndSchedule @ index.esm2017.js:13316
enqueueAfterDelay @ index.esm2017.js:16438
Mo @ index.esm2017.js:12441
wr @ index.esm2017.js:13100
await in wr (async)
Tr @ index.esm2017.js:13149
await in Tr (async)
onMessage @ index.esm2017.js:12663
(anonymous) @ index.esm2017.js:12529
(anonymous) @ index.esm2017.js:12552
(anonymous) @ index.esm2017.js:16365
(anonymous) @ index.esm2017.js:16398
Promise.then (async)
Ga @ index.esm2017.js:16398
enqueue @ index.esm2017.js:16365
enqueueAndForget @ index.esm2017.js:16343
(anonymous) @ index.esm2017.js:12552
(anonymous) @ index.esm2017.js:12529
so @ index.esm2017.js:11939
(anonymous) @ index.esm2017.js:12163
(anonymous) @ index.esm2017.js:12114
Te @ index.esm2017.js:27
Se @ index.esm2017.js:25
Ma.wa @ index.esm2017.js:86
Bt @ index.esm2017.js:43
Ot @ index.esm2017.js:38
a.Ia @ index.esm2017.js:36
a.gb @ index.esm2017.js:34
Te @ index.esm2017.js:27
Se @ index.esm2017.js:25
Gn @ index.esm2017.js:65
a.cb @ index.esm2017.js:64
a.Fa @ index.esm2017.js:64
Nn @ index.esm2017.js:60
a.Sa @ index.esm2017.js:58
Promise.then (async)
jn @ index.esm2017.js:58
a.Sa @ index.esm2017.js:58
Promise.then (async)
jn @ index.esm2017.js:58
a.Va @ index.esm2017.js:58
Promise.then (async)
a.send @ index.esm2017.js:55
a.ea @ index.esm2017.js:62
St @ index.esm2017.js:33
ba @ index.esm2017.js:78
a.Ga @ index.esm2017.js:77
Fe @ index.esm2017.js:28
Promise.then (async)
Ce @ index.esm2017.js:28
Be @ index.esm2017.js:28
da @ index.esm2017.js:76
Bt @ index.esm2017.js:43
Ot @ index.esm2017.js:38
a.Ia @ index.esm2017.js:36
a.gb @ index.esm2017.js:34
Te @ index.esm2017.js:27
Se @ index.esm2017.js:25
Gn @ index.esm2017.js:65
a.cb @ index.esm2017.js:64
a.Fa @ index.esm2017.js:64
Nn @ index.esm2017.js:60
a.Sa @ index.esm2017.js:58
Promise.then (async)
jn @ index.esm2017.js:58
a.Va @ index.esm2017.js:58
Promise.then (async)
a.send @ index.esm2017.js:55
a.ea @ index.esm2017.js:62
St @ index.esm2017.js:33
At @ index.esm2017.js:33
a.Ha @ index.esm2017.js:74
Fe @ index.esm2017.js:28
Promise.then (async)
Ce @ index.esm2017.js:28
Be @ index.esm2017.js:28
_a.m @ index.esm2017.js:84
Wr @ index.esm2017.js:12106
send @ index.esm2017.js:11930
Fo @ index.esm2017.js:12444
Zo @ index.esm2017.js:12676
Ar @ index.esm2017.js:13135
(anonymous) @ index.esm2017.js:12525
(anonymous) @ index.esm2017.js:12552
(anonymous) @ index.esm2017.js:16365
(anonymous) @ index.esm2017.js:16398
Promise.then (async)
Ga @ index.esm2017.js:16398
enqueue @ index.esm2017.js:16365
enqueueAndForget @ index.esm2017.js:16343
(anonymous) @ index.esm2017.js:12552
(anonymous) @ index.esm2017.js:12524
eo @ index.esm2017.js:11933
(anonymous) @ index.esm2017.js:12172
setTimeout (async)
lo @ index.esm2017.js:12167
Go @ index.esm2017.js:12652
qo @ index.esm2017.js:12523
(anonymous) @ index.esm2017.js:12513
Promise.then (async)
auth @ index.esm2017.js:12504
start @ index.esm2017.js:12409
start @ index.esm2017.js:12646
Mr @ index.esm2017.js:13131
wr @ index.esm2017.js:13107
await in wr (async)
ni @ index.esm2017.js:14325
await in ni (async)
(anonymous) @ index.esm2017.js:18817
await in (anonymous) (async)
(anonymous) @ index.esm2017.js:16365
(anonymous) @ index.esm2017.js:16398
Promise.then (async)
Ga @ index.esm2017.js:16398
enqueue @ index.esm2017.js:16365
enqueueAndForget @ index.esm2017.js:16343
(anonymous) @ index.esm2017.js:18817
qc @ index.esm2017.js:18815
Dc @ index.esm2017.js:18725
(anonymous) @ Game.vue:1054
ze @ runtime-core.esm-bundler.js:155
Ve @ runtime-core.esm-bundler.js:164
p @ runtime-core.esm-bundler.js:1779
ht @ runtime-core.esm-bundler.js:328
mt @ runtime-core.esm-bundler.js:369
Promise.then (async)
dt @ runtime-core.esm-bundler.js:285
st @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
T @ reactivity.esm-bundler.js:382
S @ reactivity.esm-bundler.js:355
(anonymous) @ reactivity.esm-bundler.js:509
(anonymous) @ index.js:2636
Promise.then (async)
setHealing @ index.js:2634
(anonymous) @ vuex.esm-browser.js:298
(anonymous) @ vuex.esm-browser.js:982
(anonymous) @ vuex.esm-browser.js:981
Z._withCommit @ vuex.esm-browser.js:1139
Z.commit @ vuex.esm-browser.js:980
commit @ vuex.esm-browser.js:917
(anonymous) @ HealersHut.vue:343
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
a @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ HealersHut.vue:320
a.isDead.a.needsHeal.a.isDCAUApproved.a.hasDCAU.a.isHealing.a.isFetchingHealPrice.Object.onClick.t.<computed>.t.<computed> @ HealersHut.vue:79
(anonymous) @ runtime-dom.esm-bundler.js:383
ze @ runtime-core.esm-bundler.js:155
Ve @ runtime-core.esm-bundler.js:164
Ve @ runtime-core.esm-bundler.js:174
n @ runtime-dom.esm-bundler.js:369
Game.vue:990 refreshing
inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
await in _processRequest (async)
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
(anonymous) @ inpage.js:1
request @ inpage.js:1
(anonymous) @ web3-provider.js:65
send @ web3-provider.js:129
(anonymous) @ json-rpc-provider.js:515
(anonymous) @ json-rpc-provider.js:8
h @ json-rpc-provider.js:4
perform @ json-rpc-provider.js:492
(anonymous) @ base-provider.js:1531
c @ base-provider.js:5
Promise.then (async)
s @ base-provider.js:7
c @ base-provider.js:5
Promise.then (async)
s @ base-provider.js:7
(anonymous) @ base-provider.js:8
g @ base-provider.js:4
estimateGas @ base-provider.js:1526
sendUncheckedTransaction @ json-rpc-provider.js:187
(anonymous) @ json-rpc-provider.js:231
c @ json-rpc-provider.js:5
Promise.then (async)
s @ json-rpc-provider.js:7
(anonymous) @ json-rpc-provider.js:8
h @ json-rpc-provider.js:4
sendTransaction @ json-rpc-provider.js:227
(anonymous) @ index.js:323
c @ index.js:5
Promise.then (async)
s @ index.js:7
(anonymous) @ index.js:8
h @ index.js:4
(anonymous) @ index.js:312
(anonymous) @ HealersHut.vue:326
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
a @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ HealersHut.vue:320
a.isDead.a.needsHeal.a.isDCAUApproved.a.hasDCAU.a.isHealing.a.isFetchingHealPrice.Object.onClick.t.<computed>.t.<computed> @ HealersHut.vue:79
(anonymous) @ runtime-dom.esm-bundler.js:383
ze @ runtime-core.esm-bundler.js:155
Ve @ runtime-core.esm-bundler.js:164
Ve @ runtime-core.esm-bundler.js:174
n @ runtime-dom.esm-bundler.js:369
HealersHut.vue:347 {code: -32603, message: 'Internal JSON-RPC error.', data: {…}, stack: '{\n  "code": -32603,\n  "message": "Internal JSON-RP…hfbeogaeaoehlefnkodbefgpgknn/common-6.js:19:37692'}code: -32603data: {code: 3, message: 'execution reverted: DIRECT_HEAL_DISALLOWED', data: '0x08c379a00000000000000000000000000000000000000000…845414c5f444953414c4c4f57454400000000000000000000'}message: "Internal JSON-RPC error."stack: "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: DIRECT_HEAL_DISALLOWED\",\n    \"data\": \"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000164449524543545f4845414c5f444953414c4c4f57454400000000000000000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:322950)\\n    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:325706)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:326316)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:22:17293)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:22:18322\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:19:37692\"\n}\n  at new r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:322950)\n  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:325706)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:326316)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:22:17293)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:22:18322\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:19:37692"[[Prototype]]: Object
helpers.js:13 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000164449524543545f4845414c5f444953414c4c4f57454400000000000000000000
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed here: https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/commit/b63017c96a175f7e24729030eb949c56c791ca63
