### ISSUE TITLE
[Bug]: Stuck on "checking session"

### ISSUE THREAD

**Issue by benpatterson1** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

BenGK🔰#4861

### What happened?

I have chrome with metamask and xDEFI extensions on.

I logged in once successfully, then refreshed the page and still was completely stuck on this page (see screenshot)

![image](https://user-images.githubusercontent.com/2111036/209255631-737961eb-4a98-4562-9f4d-10968dcebd85.png)

I am able to workaround by clearing cache and relogging.

I am able to reproduce with page refreshes intermittently, but its not super clear what causes it. 
Perhaps interestingly, I was unable to press the "accept quest" on that first login. The second time it happened I was claiming 3 items from the stash and the contract interaction hung, leaving the UI unresponsive. 

Happy to jump on a call and reproduce.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output / error message

```shell
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://hmeobnfnfcmdkdcmlblgagmfpfboieaf/js/contentScript.bundle.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
VM291:2 XDEFI: Failed to process message TypeError: Cannot read properties of undefined (reading 'info')
t.log @ VM291:2
i._write @ VM291:2
g @ VM291:2
(anonymous) @ VM291:2
m.write @ VM291:2
l @ VM291:2
o.emit @ VM291:2
A @ VM291:2
O @ VM291:2
k.push @ VM291:2
f.push @ VM291:2
value @ VM291:2
f._read @ VM291:2
f._write @ VM291:2
O @ VM291:2
(anonymous) @ VM291:2
k.write @ VM291:2
Object.keys.forEach.t.<computed> @ VM291:2
(anonymous) @ VM291:2
o.emit @ VM291:2
x @ VM291:2
y @ VM291:2
v.push @ VM291:2
t._onMessage @ VM291:2
postMessage (async)
t._write @ contentScript.bundle.js:2
m @ contentScript.bundle.js:2
y @ contentScript.bundle.js:2
g.uncork @ contentScript.bundle.js:2
t._onMessage @ contentScript.bundle.js:2
postMessage (async)
t._write @ VM291:2
t._onMessage @ VM291:2
postMessage (async)
t._write @ contentScript.bundle.js:2
t @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
m @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
m @ contentScript.bundle.js:2
_ @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
Promise.then (async)
(anonymous) @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
(anonymous) @ contentScript.bundle.js:2
play-beta:1 Access to fetch at 'https://load-dcg.herokuapp.com/sessiondetails' from origin 'https://stage.aurumdraconis.dragoncrypto.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
LoginLoading.vue:667          POST https://load-dcg.herokuapp.com/sessiondetails net::ERR_FAILED
(anonymous) @ LoginLoading.vue:667
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
a @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ LoginLoading.vue:652
(anonymous) @ LoginLoading.vue:733
f @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
a @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
Promise.then (async)
a @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
ze @ runtime-core.esm-bundler.js:155
Ve @ runtime-core.esm-bundler.js:164
t.__weh.t.__weh @ runtime-core.esm-bundler.js:2685
pt @ runtime-core.esm-bundler.js:356
mt @ runtime-core.esm-bundler.js:401
Promise.then (async)
dt @ runtime-core.esm-bundler.js:285
st @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
T @ reactivity.esm-bundler.js:382
Ce @ reactivity.esm-bundler.js:990
(anonymous) @ reactivity.esm-bundler.js:1113
T @ reactivity.esm-bundler.js:382
Ce @ reactivity.esm-bundler.js:990
set value @ reactivity.esm-bundler.js:1026
V @ vue-router.esm-bundler.js:3194
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
F @ vue-router.esm-bundler.js:3038
C @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:3834
56d7 @ main.js:13
o @ bootstrap:89
0 @ app.c7add136.js:1
o @ bootstrap:89
n @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.c7add136.js:1
runtime-core.esm-bundler.js:226 TypeError: Failed to fetch
    at LoginLoading.vue:667:36
    at f (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at a (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:25:9)
Ke @ runtime-core.esm-bundler.js:226
Ge @ runtime-core.esm-bundler.js:204
(anonymous) @ runtime-core.esm-bundler.js:167
Promise.catch (async)
Ve @ runtime-core.esm-bundler.js:166
t.__weh.t.__weh @ runtime-core.esm-bundler.js:2685
pt @ runtime-core.esm-bundler.js:356
mt @ runtime-core.esm-bundler.js:401
Promise.then (async)
dt @ runtime-core.esm-bundler.js:285
st @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
T @ reactivity.esm-bundler.js:382
Ce @ reactivity.esm-bundler.js:990
(anonymous) @ reactivity.esm-bundler.js:1113
T @ reactivity.esm-bundler.js:382
Ce @ reactivity.esm-bundler.js:990
set value @ reactivity.esm-bundler.js:1026
V @ vue-router.esm-bundler.js:3194
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
F @ vue-router.esm-bundler.js:3038
C @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:3834
56d7 @ main.js:13
o @ bootstrap:89
0 @ app.c7add136.js:1
o @ bootstrap:89
n @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.c7add136.js:1
.png:1          GET https://cdn.dragoncrypto.io/encounters/.png 404
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by benpatterson1** [comment]
expanding on this a bit... 
![image](https://user-images.githubusercontent.com/2111036/209261908-ef872c6e-198d-447f-9677-fbfcf0161664.png)

able to reproduce fairly quickly.. completely stops me from playing after ~3min... the websocket and chat throw errors in the console and then refreshing the page is the above mentioned problem... However, hard cache refresh isn't working now.

**Comment by Polypup** [comment]
Yes, we're having an issue that we're working on which crashing the server. We're aware of the bug and working to resolve.
