### ISSUE TITLE
[Bug]:  Cannot claim specific equipment item from stash

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#21]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

1. Opened stash after winning battle
2. Clicked sword
3. Clicked claim

### Relevant log output / error message

```shell
helpers.js?2fa3:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at parseError (helpers.js?2fa3:14:1)
    at _callee11$ (StashInventory.vue?090c:566:1)
    at h (inpage.js:112:55306)
    at Generator._invoke (inpage.js:112:55059)
    at Generator.throw (inpage.js:112:55669)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3:1)
    at _throw (asyncToGenerator.js?1da1:29:1)
```
```


### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Token already minted error. Disregard
