### ISSUE TITLE
[Bug]: buy a song err.

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#325]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

![image](https://user-images.githubusercontent.com/121979441/211917425-eb2bb58e-eb80-4c1f-afc7-f9e7c74b4d39.png)

occured while trying to buy a song.

### What browsers are you seeing the problem on?

Brave

### Relevant log output / error message

```shell
1008 1 undefined undefined
app.03b2fda3.js:1 TypeError: Cannot read properties of undefined (reading 'toHexString')
    at c (chunk-vendors.aa13d72c.js:2114:303785)
    at u (chunk-vendors.aa13d72c.js:2114:304573)
    at m.encode (chunk-vendors.aa13d72c.js:2114:349071)
    at chunk-vendors.aa13d72c.js:2114:346927
    at Array.forEach (<anonymous>)
    at b (chunk-vendors.aa13d72c.js:2114:346869)
    at M.encode (chunk-vendors.aa13d72c.js:2114:351336)
    at R.encode (chunk-vendors.aa13d72c.js:2114:352862)
    at v._encodeParams (chunk-vendors.aa13d72c.js:2249:131197)
    at v.encodeFunctionData (chunk-vendors.aa13d72c.js:2249:132143)
app.03b2fda3.js:1 1008 1 undefined undefined
app.03b2fda3.js:1 TypeError: Cannot read properties of undefined (reading 'toHexString')
    at c (chunk-vendors.aa13d72c.js:2114:303785)
    at u (chunk-vendors.aa13d72c.js:2114:304573)
    at m.encode (chunk-vendors.aa13d72c.js:2114:349071)
    at chunk-vendors.aa13d72c.js:2114:346927
    at Array.forEach (<anonymous>)
    at b (chunk-vendors.aa13d72c.js:2114:346869)
    at M.encode (chunk-vendors.aa13d72c.js:2114:351336)
    at R.encode (chunk-vendors.aa13d72c.js:2114:352862)
    at v._encodeParams (chunk-vendors.aa13d72c.js:2249:131197)
    at v.encodeFunctionData (chunk-vendors.aa13d72c.js:2249:132143)
app.03b2fda3.js:1 1008 1 undefined undefined
app.03b2fda3.js:1 TypeError: Cannot read properties of undefined (reading 'toHexString')
    at c (chunk-vendors.aa13d72c.js:2114:303785)
    at u (chunk-vendors.aa13d72c.js:2114:304573)
    at m.encode (chunk-vendors.aa13d72c.js:2114:349071)
    at chunk-vendors.aa13d72c.js:2114:346927
    at Array.forEach (<anonymous>)
    at b (chunk-vendors.aa13d72c.js:2114:346869)
    at M.encode (chunk-vendors.aa13d72c.js:2114:351336)
    at R.encode (chunk-vendors.aa13d72c.js:2114:352862)
    at v._encodeParams (chunk-vendors.aa13d72c.js:2249:131197)
    at v.encodeFunctionData (chunk-vendors.aa13d72c.js:2249:132143)
app.03b2fda3.js:1 Uncaught TypeError: i.value.pause is not a function
    at app.03b2fda3.js:1:502165
play-beta:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
app.03b2fda3.js:1 Uncaught TypeError: i.value.pause is not a function
    at app.03b2fda3.js:1:502165
api-js.mixpanel.com/track/?verbose=1&ip=1&_=1673470972611:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
api-js.mixpanel.com/track/?verbose=1&ip=1&_=1673470977748:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
api-js.mixpanel.com/track/?verbose=1&ip=1&_=1673470982860:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
api-js.mixpanel.com/track/?verbose=1&ip=1&_=1673470987876:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.03b2fda3.js:1 1008 1 undefined undefined
app.03b2fda3.js:1 TypeError: Cannot read properties of undefined (reading 'toHexString')
    at c (chunk-vendors.aa13d72c.js:2114:303785)
    at u (chunk-vendors.aa13d72c.js:2114:304573)
    at m.encode (chunk-vendors.aa13d72c.js:2114:349071)
    at chunk-vendors.aa13d72c.js:2114:346927
    at Array.forEach (<anonymous>)
    at b (chunk-vendors.aa13d72c.js:2114:346869)
    at M.encode (chunk-vendors.aa13d72c.js:2114:351336)
    at R.encode (chunk-vendors.aa13d72c.js:2114:352862)
    at v._encodeParams (chunk-vendors.aa13d72c.js:2249:131197)
    at v.encodeFunctionData (chunk-vendors.aa13d72c.js:2249:132143)
app.03b2fda3.js:1 1008 1 undefined undefined
app.03b2fda3.js:1 TypeError: Cannot read properties of undefined (reading 'toHexString')
    at c (chunk-vendors.aa13d72c.js:2114:303785)
    at u (chunk-vendors.aa13d72c.js:2114:304573)
    at m.encode (chunk-vendors.aa13d72c.js:2114:349071)
    at chunk-vendors.aa13d72c.js:2114:346927
    at Array.forEach (<anonymous>)
    at b (chunk-vendors.aa13d72c.js:2114:346869)
    at M.encode (chunk-vendors.aa13d72c.js:2114:351336)
    at R.encode (chunk-vendors.aa13d72c.js:2114:352862)
    at v._encodeParams (chunk-vendors.aa13d72c.js:2249:131197)
    at v.encodeFunctionData (chunk-vendors.aa13d72c.js:2249:132143)
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Server was just reset. Refresh and you should be fine.
