### ISSUE TITLE
[Bug]: Crafting caused server to crash

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

```
inputResourceIds [ 20041, 20002 ]
/app/node_modules/@azure/storage-blob/dist/index.js:13952
throw new Error("Unable to extract accountName with provided information.");
Error: Unable to extract accountName with provided information.
at getAccountNameFromUrl (/app/node_modules/@azure/storage-blob/dist/index.js:13952:15)
at new StorageClient (/app/node_modules/@azure/storage-blob/dist/index.js:15484:28)
at new BlobServiceClient (/app/node_modules/@azure/storage-blob/dist/index.js:24538:9)
at Object.checkBlobExists (/app/data/AzureStorage.js:39:24)
at Object.createTintedImage (/app/data/ImageProcessor.js:12:43)
at Object.convertBlueprintToItemData (/app/GameCategories/Crafting.js:161:42)
at Object.craftFromBlueprint (/app/GameCategories/Crafting.js:102:40)
at /app/app.js:4312:47
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Seems like an issue while generating the crafted item’s image while using the api?

**Comment by Polypup** [comment]
Yes, it's very strange because this should have been resolved. Maybe something happened to our Azure server? I'm trying to replicate now.

**Comment by Polypup** [comment]
<img width="436" alt="Screenshot 2022-11-29 at 4 46 01 PM" src="https://user-images.githubusercontent.com/85349906/204654893-cd540b4b-18f7-4be9-baad-918f8eb39926.png">

The `AZURE_CONNECTION_STRING` was never added to the `hero_api` config vars. It's resolved locally. I sent a question to the slack to make sure we get it added.
